# Root BUILD definitions for Project Ion.

package(
  default_visibility = ["//visibility:public"],
)

# 3rd-party libraries.
# TODO - move to //external

java_import(
  name = "jackson",
  jars = [
    "jackson-annotations-2.5.0.jar",
    "jackson-core-2.5.0.jar",
    "jackson-databind-2.5.0.jar",
  ],
)
